# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 00:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_list_item_unique_together'),
        ('lists', '0005_auto_20170518_2039'),
    ]

    operations = [
    ]
